services:
    # This sets up the Database to use in the project
    database:
        image: postgres:17
        container_name: gm-notes-database
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD
        volumes:
            - db_data:/var/lib/postgresql/data #named:path
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
            interval: 5s
            timeout: 5s
            retries: 5
    backend:
        build: ./backend
        container_name: gm-notes-backend
        ports:
            - 8000:8000
        env_file: .env
        environment: 
            - POSTGRES_HOST=database
        depends_on: { database: { condition: service_healthy } }
        volumes:
            - ./backend:/app
    frontend:
        build: ./frontend
        container_name: gm-notes-frontend
        ports: 
            - 5173:5173
        environment: 
            - API_PROXY_TARGET=http://backend:8000
        depends_on: [backend]
        volumes:
            - ./frontend:/app
            - /app/node_modules

# top-level key, sibling of `services`
volumes:
    db_data: