# Generated by Django 6.0.7 on 2026-07-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_environment_puzzle_puzzlesolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='hazards',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='secrets',
            field=models.TextField(blank=True),
        ),
    ]
