# Generated by Django 6.0.7 on 2026-07-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_environment_hazards_environment_secrets'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='acts', to='campaigns.actor'),
        ),
    ]
