# Generated by Django 6.0.7 on 2026-07-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_act_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='environments',
            field=models.ManyToManyField(blank=True, related_name='acts', to='campaigns.environment'),
        ),
        migrations.AddField(
            model_name='act',
            name='puzzles',
            field=models.ManyToManyField(blank=True, related_name='acts', to='campaigns.puzzle'),
        ),
    ]
