# Generated by Django 6.0.7 on 2026-07-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_act_environments_act_puzzles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready')], default='draft', max_length=20),
        ),
    ]
