# Generated by Django 6.0.7 on 2026-07-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_alter_puzzle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='actor_type',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='actor',
            name='factions',
            field=models.JSONField(blank=True, default=[]),
        ),
        migrations.AddField(
            model_name='actor',
            name='tier',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='environment',
            name='environment_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='environment',
            name='tier',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
