# Generated by Django 6.0.7 on 2026-07-30 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_add_tier_type_factions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='factions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
