# Generated by Django 6.0.7 on 2026-07-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_add_tier_type_factions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='actor',
            name='tier',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
